### ISSUE TITLE
On the numerical accuracy of imMinkowski

### ISSUE THREAD

**Issue by yuanshuoastro** [mattools/matImage#2]
Hello,
I am looking for a fast and best method/code to get the Minkowski functionals from a 2D figure. Reading your paper on it, I found that you mentioned the numerical accuracy is not perfect. Could you suggest some ways to improve by using your code, like add pixies or ... ?

By the way, what is the best algorithm to calculate Minkowski functionals from a 2D?

**Comment by dlegland** [comment]
Hello,

The code implemented in this Matlab version uses local configuration to estimate Minkowski functionals from a discrete grid. As the structure of interest is observed through a discretization scheme, there will always be a difference between the estimate and the real value.

A short comparison of methods:
* counting boundary pixels, eventually weighted (like in ImageJ), usually results in strong biases
* Crofton methon, or more generally methods based on counting local configurations of pixels/voxels have my preference, but may produce up to 10% relative errors when objects have straight boundaries (like rectangle). When the estimates are repeated over various orientations and relative positioning, the average of the estimates is rather accurate.
* other possibilites are "multi-grid convergent" methods. I do not know about their implementation in Matlab. 

So, I would advise using Crofton-based methods.

Hope this helps?

**Comment by yuanshuoastro** [comment]
Thank you!
Sorry so late.
Your answer is really heplful!
Best
