### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by apjanke** [mattools/matImage#3]
There’s no `LICENSE` file in this or the other mattools repos. What license are they published under?

**Comment by dlegland** [comment]
Hi,

It was originally distributed as LGPL, then Mathworks enforced a BSD like license. However I'm not sure there is still an obligation to conform to BSD license. 
I'll check this, but final choice would be a free license, either LGPL or BSD

**Comment by apjanke** [comment]
Are you talking about the MathWorks File Exchange license requirements? My understanding is that if you want to publish something directly on File Exchange, it has to be BSD 2-clause, but if you use their "Link to GitHub repo" option, [it can be any FLOSS license](https://www.mathworks.com/matlabcentral/FX_transition_faq.html#Different_license).

**Comment by dlegland** [comment]
yes, exactly! Thanks for the link.
The MatTools library was originally contributed as "file copied from the computer", so I think BSD is still the best choice.
I'm fine with BSD-2 clause license for other contributions as well, so I will update the different projects.

**Comment by apjanke** [comment]
👍
